### ISSUE TITLE
Percy Snapshot to Rendering Correctly

### ISSUE THREAD

**Issue by SC7639** [percy/percy-script#18]
I'm having some weird characters and styling with my snapshots vs what is shown in the browser and puppeteer screenshots.

Puppeteer Screenshot:
![Highest Point](https://user-images.githubusercontent.com/6049560/98799824-86cec180-2407-11eb-95a2-f198f28d02e7.png)

PercySnapshot:
![be37c28f5fc9efee4d6b461ed65d7738aec0d9a510161c46b55739ae61994985](https://user-images.githubusercontent.com/6049560/98800082-ce554d80-2407-11eb-8488-316b2f09a31b.png)

**Comment by wwilsman** [comment]
Hi @SC7639!

That usually means that the page is missing `<meta charset="utf-8">` at the top of the head element. When Percy re-renders the page in its own infrastructure, the browser will incorrectly guess the charset when that tag is missing.

If you do have that tag in the head, it could be that invalid head elements are causing the browser to "correct" the HTML when re-rendering causing head elements to be pushed into the body element.

Since this issue isn't related to this SDK, I'm going to close it. But feel free to reach out to [support](https://www.browserstack.com/contact?ref=percy#technical-support) where we'll be more than happy to help debug snapshot issues such as this! 😃
